### ISSUE TITLE
I have made a mistake. Could you please help me check it

### ISSUE THREAD

**Issue by ghost** [tuliren/publish-gitbook#3]
![image](https://user-images.githubusercontent.com/39549827/84381010-eb98ac80-ac1a-11ea-84ef-be69d004319c.png)

FileNotFoundError: No "README" file (or is ignored)
fatal: Not a git repository (or any parent up to mount point /github/workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /github/workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /github/workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /github/workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cp: cannot stat '_book/*': No such file or directory

**Comment by tuliren** [comment]
@fullstack-zhangpeng, sure. I can take a look. Which repo is this (if it is a public repo)? It would be hard to debug without more context.

**Comment by ghost** [comment]
this repo: https://github.com/fullstack-zhangpeng/blog , thx!

**Comment by tuliren** [comment]
Got it.

Your [main.yml](https://github.com/fullstack-zhangpeng/blog/blob/master/.github/workflows/main.yml) is missing the checkout action. Without this action, no code is pulled from the repo. That's why it is complaining that there is no README file.

Here is the missing action:
```yml
- name: Checkout repo
  uses: actions/checkout@v1
```

You can follow the example in the [README](https://github.com/tuliren/publish-gitbook).

**Comment by ghost** [comment]
Thank you very much
